apiVersion: v1
kind: ServiceAccount
metadata:
  name: ksa-storage-reader
  namespace: mon-namespace
  annotations:
    iam.gke.io/gcp-service-account: gsa-storage-reader@mon-projet-gcp.iam.gserviceaccount.com